"""Bundle src/ modules + a notebook driver into one self-contained Kaggle kernel script.

Why this exists: NB01 depended on `sys.path.insert(0, "/kaggle/input/er-code")`
+ `from src import eda`, and hit `ModuleNotFoundError: No module named 'src'`
even though the `er-code` dataset was correctly attached — the mount layout
didn't match what the notebook assumed. Per project decision, every pushed
kernel must be fully self-contained: no `sys.path` tricks, no dependency on a
code dataset being mounted a particular way.

`src/` stays the single source of truth for local development and pytest.
This tool inlines the exact text of the needed `src/*.py` modules into one
generated script (as real, importable in-memory module objects wired
together at kernel start), plus the notebook's own driver code. Edit the
source modules or the driver, then re-run the bundler — never edit a
generated file directly (its own docstring says so too).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "code" / "business_entity_resolution" / "src"

_RELATIVE_IMPORT_RE = re.compile(r"^from \.\s+import\s+.+$\n?", re.MULTILINE)


def _strip_relative_imports(source: str) -> str:
    """Remove `from . import X` lines (intra-src imports) from a module's source.

    The bundle wires modules together directly as module objects (see
    `bundle()`), so these relative imports would fail with no package context
    and must be stripped before embedding.

    Inputs: source - a src/*.py file's text.
    Outputs: the same text with relative-import lines removed.
    """
    return _RELATIVE_IMPORT_RE.sub("", source)


def bundle(
    module_names: list[str], driver_source: str, config_text: str | None = None, defines: dict | None = None
) -> str:
    """Build one self-contained script from src/ modules plus a driver's code.

    Each module is embedded as its exact source text (via `repr()`, so no
    escaping bugs) and exec'd into its own `types.ModuleType` at kernel start;
    modules are wired to each other as plain attributes first, so existing
    calls like `io_utils.load_tsv(...)` inside `eda.py` keep working
    unmodified. The result imports nothing beyond the Python standard library
    and whatever third-party packages the modules themselves import (numpy,
    pandas, rapidfuzz, ...), which the Kaggle base image already has.

    Inputs: module_names - src/ module stems in dependency order (a module
            that others depend on must come first), e.g. ["io_utils", "eda"];
            driver_source - the notebook's own driving code, referencing the
            bundled modules by bare name (e.g. `eda.run_eda(...)`); must not
            `sys.path.insert(...)` or `from src import ...`;
            config_text - optional YAML text (src/configs/default.yaml), exposed
            to the driver as the parsed dict `CONFIG`; defines - optional
            {NAME: value} globals set before the driver (e.g. {"DRY_RUN": true}
            so a dry-run kernel can share the full kernel's driver.py).
    Outputs: the full generated script text, ready to write to a kernel's code_file.
    """
    lines = [
        '"""Auto-generated, self-contained Kaggle kernel script.',
        "",
        f"Bundled by tools/bundle_kernel.py from: {', '.join(module_names)} (src/*.py).",
        "DO NOT EDIT THIS FILE DIRECTLY. Edit the source module(s) under",
        "code/business_entity_resolution/src/, or driver.py in this folder,",
        "then re-run: python tools/bundle_kernel.py --spec <this folder>/bundle_spec.json",
        '"""',
        "",
        "import sys",
        "import types",
        "",
    ]
    for name in module_names:
        source = (SRC_DIR / f"{name}.py").read_text(encoding="utf-8")
        source = _strip_relative_imports(source)
        lines.append(f"_{name}_source = {source!r}")
        lines.append(f'{name} = types.ModuleType({name!r})')
        # Registered in sys.modules so pickle (multiprocessing) can resolve
        # functions defined in the bundled module by "<module>.<name>".
        lines.append(f"sys.modules[{name!r}] = {name}")
    # Wire cross-module references (e.g. eda needs io_utils) before exec: a
    # module's function bodies look up free names in its __dict__ only when
    # *called*, not when defined, so injecting first is simplest and safe.
    for name in module_names:
        for dep in module_names:
            if dep != name:
                lines.append(f"{name}.__dict__[{dep!r}] = {dep}")
    for name in module_names:
        lines.append(f'exec(compile(_{name}_source, {name + ".py"!r}, "exec"), {name}.__dict__)')
    if config_text is not None:
        lines.append("import yaml")
        lines.append(f"CONFIG = yaml.safe_load({config_text!r})")
    for key, value in (defines or {}).items():
        lines.append(f"{key} = {value!r}")
    lines.append("")
    lines.append("# ---- notebook driver (see driver.py in this kernel's folder) ----")
    lines.append(driver_source)
    return "\n".join(lines)


def bundle_from_spec(spec_path: Path) -> Path:
    """Read a kernel folder's `bundle_spec.json` and (re)generate its self-contained script.

    Inputs: spec_path - path to a `bundle_spec.json` with keys "modules"
            (list of src/ module stems, dependency order), "driver" (filename
            in the same folder), "output" (filename in the same folder;
            must match kernel-metadata.json's `code_file`), and optionally
            "config": true to inline src/configs/default.yaml as `CONFIG`, and
            "defines": {NAME: value} globals for the driver. "driver" may be a
            relative path into a sibling folder (dry-run kernels share it).
    Outputs: path to the written generated script.
    """
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    kernel_dir = spec_path.parent
    driver_source = (kernel_dir / spec["driver"]).read_text(encoding="utf-8")
    config_text = None
    if spec.get("config"):
        config_text = (SRC_DIR / "configs" / "default.yaml").read_text(encoding="utf-8")
    script = bundle(spec["modules"], driver_source, config_text, spec.get("defines"))
    out_path = kernel_dir / spec["output"]
    out_path.write_text(script, encoding="utf-8")
    return out_path


def main() -> None:
    """CLI: `python tools/bundle_kernel.py --spec <kernel_dir>/bundle_spec.json`."""
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", required=True)
    args = parser.parse_args()
    out = bundle_from_spec(Path(args.spec))
    print(f"Bundled -> {out}")


if __name__ == "__main__":
    main()
